In [1]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.0+cu116


#scaler tensor:


In [2]:
scaler=torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
scaler.item()

7

In [5]:
#vecotr:
vector=torch.tensor([1,2,3])

In [6]:
vector.shape

torch.Size([3])

#Matrix:


In [7]:
Matrix=torch.tensor([[1,2],[3,4]])

In [8]:
Matrix.shape

torch.Size([2, 2])

In [9]:
Matrix.ndim

2

In [10]:
Matrix[0]

tensor([1, 2])

In [11]:
Matrix[0][0]

tensor(1)

#tensor

In [12]:
  Tensor=torch.tensor([[[1,2],[3,4]]])

In [13]:
Tensor.shape

torch.Size([1, 2, 2])

In [14]:
Tensor.ndim

3

#random tensors:


In [15]:
randomTensor=torch.rand(3,4)

In [16]:
randomTensor

tensor([[0.7285, 0.9013, 0.4433, 0.1771],
        [0.7820, 0.7338, 0.5077, 0.5948],
        [0.5897, 0.4922, 0.8010, 0.3532]])

In [17]:
randomTensor.ndim

2

In [18]:
zero_tensor=torch.zeros(size=(3,3))

In [19]:
zero_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [20]:
ones=torch.ones(size=(2,2))

In [21]:
ones

tensor([[1., 1.],
        [1., 1.]])

In [22]:
##making tensor range and tensor looks like another tensor



```
##making tensor range and tensor looks like another tensor```#



In [23]:
range_tensor=torch.arange(0,10)

In [24]:
range_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
like_tensor=torch.zeros_like(range_tensor)

In [26]:
like_tensor

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
#tensor data types

#tensor data types

In [28]:
float_32_tensor=torch.tensor([3.0,2.0,4.000],requires_grad=False,device=None)


In [29]:
float_32_tensor

tensor([3., 2., 4.])

In [30]:
float_32_tensor.dtype

torch.float32

In [31]:
float_32_tensor.device

device(type='cpu')

##manipulating Tensors

In [32]:
tensor_1=torch.tensor([1,2,3])

In [33]:
tensor_1*tensor_1

tensor([1, 4, 9])

In [34]:
 torch.matmul(tensor_1,tensor_1)

tensor(14)

In [35]:
t2=tensor_1.T

<ipython-input-35-100723eccbc6>:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3277.)
  t2=tensor_1.T


In [36]:
torch.matmul(tensor_1,t2)

tensor(14)

##maen max sum of 

In [50]:
v=torch.tensor([1,2,3,4,5])

In [40]:
v.max()

tensor(5)

In [41]:
v.min()

tensor(1)

In [42]:
v.sum()

tensor(15)

In [49]:
torch.mean(v.type(torch.float32))

tensor(3.)

## finding the index of the max and min

In [51]:
v.argmin()

tensor(0)

In [52]:
v.argmax()

tensor(4)